Hotfix/docker build permissions
hmhco/keepsake pull request #4
Opened 2018-02-23 22:16 UTC by kytomaki

Mounting docker volume proved to be problematic. This sidesteps it by building the rpm on the docker image build phase. Then instantiating the container and copying the rpm from there.

2018-02-23 22:47 UTC, jaakkoo requested changes
Typos like "Developmen" .. 

So do we need to build Docker image to build a rpm?

2018-02-23 22:47 UTC, jaakkoo commented on Makefile
> +		--name $(AMAZONLINUX_VERSION)-Developmen-$(PID) \
Developmen

2018-02-23 22:47 UTC, jaakkoo commented on Makefile
> +PID := $$$$
???

2018-02-26 15:31 UTC, kytomaki commented
This shouldn't be needed any more.

2018-02-26 15:31 UTC, closed without merging